version: "3.9"

services:
  db_products:
    image: mariadb:11.2.3
    restart: always
    environment:
      MARIADB_USER: springuser
      MARIADB_PASSWORD: ThePassword
      MARIADB_DATABASE: db_products
      MARIADB_ROOT_PASSWORD: ThePassword
    #volumes:
    #  - ./data:/var/lib/mysql
    ports:
      - "3308:3306"
    container_name: db_products
    labels:
      - "traefik.enable=false"

    networks:
      - softcont-network

  product_management:
    image: jeserna/product_management:latest
    #ports:
    #  - "8081:8080"
    environment:
      - DB_USERNAME=springuser
      - DB_PASSWORD=ThePassword
      - DB_URL=jdbc:mariadb://db_products:3306/db_products
      - SECURITY_USER=pablo
      - SECURITY_PASSWORD=1234
    depends_on:
      - db_products
    container_name: product_management
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.product_management.rule=PathPrefix(`/api/product`)"
      - "traefik.http.services.product_management.loadbalancer.server.port=8080"
    networks:
      - softcont-network

networks:
  softcont-network:
    external: true