MERGE INTO unit_of_measure (id, abbreviation, description, enterprise_id, name, state) 
KEY(id) 
VALUES 
(1, 'U', 'Unidad General', 'standart', 'Unidad General', 'true'),
(2, 'kg', 'Kilogramos', 'standart', 'Kilogramos', 'true'),
(3, 'g', 'Gramos', 'standart', 'Gramos', 'true'), 
(4, 'mg', 'Miligramos', 'standart', 'Miligramos', 'true'),
(5, 'lb', 'Libras', 'standart', 'Libras', 'true'),
(6, 'oz', 'Onzas', 'standart', 'Onzas', 'true'),
(7, 'l', 'Litros', 'standart', 'Litros', 'true'),
(8, 'ml', 'Mililitros', 'standart', 'Mililitros', 'true'),
(9, 'm³', 'Metros cúbicos', 'standart', 'Metros cúbicos', 'true'),
(10, 'cm³', 'Centímetros cúbicos', 'standart', 'Centímetros cúbicos', 'true'),
(11, 'gal', 'Galones', 'standart', 'Galones', 'true'),
(12, 'fl_oz', 'Onzas fluidas', 'standart', 'Onzas fluidas', 'true'),
(13, 'm', 'Metros', 'standart', 'Metros', 'true'),
(14, 'cm', 'Centímetros', 'standart', 'Centímetros', 'true'),
(15, 'mm', 'Milímetros', 'standart', 'Milímetros', 'true'),
(16, 'km', 'Kilómetros', 'standart', 'Kilómetros', 'true'),
(17, 'in', 'Pulgadas', 'standart', 'Pulgadas', 'true'),
(18, 'ft', 'Pies', 'standart', 'Pies', 'true'),
(19, 'yd', 'Yardas', 'standart', 'Yardas', 'true'),
(20, 'mi', 'Millas', 'standart', 'Millas', 'true'),
(21, 'm²', 'Metros cuadrados', 'standart', 'Metros cuadrados', 'true'),
(22, 'cm²', 'Centímetros cuadrados', 'standart', 'Centímetros cuadrados', 'true'),
(23, 'km²', 'Kilómetros cuadrados', 'standart', 'Kilómetros cuadrados', 'true'),
(24, 'in²', 'Pulgadas cuadradas', 'standart', 'Pulgadas cuadradas', 'true'),
(25, 'ft²', 'Pies cuadrados', 'standart', 'Pies cuadrados', 'true'),
(26, 'yd²', 'Yardas cuadradas', 'standart', 'Yardas cuadradas', 'true'),
(27, 'mi²', 'Millas cuadradas', 'standart', 'Millas cuadradas', 'true'),
(28, 'm³', 'Metros cúbicos', 'standart', 'Metros cúbicos', 'true'),
(29, 'cm³', 'Centímetros cúbicos', 'standart', 'Centímetros cúbicos', 'true'),
(30, 'km³', 'Kilómetros cúbicos', 'standart', 'Kilómetros cúbicos', 'true'),
(31, 'in³', 'Pulgadas cúbicas', 'standart', 'Pulgadas cúbicas', 'true'),
(32, 'ft³', 'Pies cúbicos', 'standart', 'Pies cúbicos', 'true'),
(33, 'yd³', 'Yardas cúbicas', 'standart', 'Yardas cúbicas', 'true'),
(34, 'mi³', 'Millas cúbicas', 'standart', 'Millas cúbicas', 'true');
